# Generated by Django 5.1.5 on 2025-01-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_telefonu', models.CharField(blank=True, max_length=12, null=True)),
                ('rodzaj_dzialalnosci', models.CharField(choices=[('P', 'Osoba prywatna'), ('J', 'Jednoosobowa działalność gospodarcza'), ('I', 'Inna forma działalności')], default='I', max_length=1)),
                ('nazwa_firmy', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ulica', models.CharField(max_length=50)),
                ('nr_budynku', models.CharField(max_length=20)),
                ('nr_lokalu', models.CharField(blank=True, max_length=20, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miejscowosc', models.CharField(max_length=60)),
                ('kraj', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stawka_vat', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_faktury', models.CharField(max_length=50, unique=True)),
                ('data_wystawienia', models.DateField()),
                ('data_sprzedazy', models.DateField()),
                ('termin_platnosci', models.DateField()),
                ('status', models.CharField(choices=[('N', 'Nieopłacona'), ('O', 'Opłacona')], default='N', max_length=1)),
                ('suma_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suma_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('podatek_vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Pozycja_na_fakturze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField()),
                ('cena_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stawka_vat', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
                ('kwota_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('kwota_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='backend.faktura')),
                ('produkt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.produkt')),
            ],
        ),
    ]
